version: '3.8'

services:
  mysql-db:
    image: mysql:5.7.31
    restart: always
    ports:
      - 3306:3306
    command: 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake_shop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes: 
      ["./mysql_data:/var/lib/mysql"]
    networks: 
      app:
        ipv4_address: 172.16.238.10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    restart: always
    ports:
      - '5000:80'
    links: 
      ["mysql-db:db"]
    networks:
      app:
        ipv4_address: 172.16.238.9

  redis-server:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks: 
      app:
        ipv4_address: 172.16.238.11

  app-backend:
    image: tim98765/unforgettable_backend:latest
    restart: always
    ports:
     - '8080:8080'
    links: 
      ["mysql-db:db","redis-server:redis"]
    depends_on: 
      ['mysql-db','redis-server']
    networks: 
      app:
        ipv4_address: 172.16.238.12
  
  app-frontend:
    build:
      context: ../
    restart: always
    ports:
      - '80:80'
    depends_on:
      ['app-backend']
    volumes: 
      ['./frontend/nginx.conf:/etc/nginx/nginx.conf']
    networks: 
      app:
        ipv4_address: 172.16.238.13
      

networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24